### PR TITLE
fix: multiple filters + pagination bug

### LINKED ISSUE #71: Combination of filters does not work
**Describe the bug**
Filtering per column works, but whenever I try to use more than one filters at the same time it does not. Could you please fix this? It worked in the initial frontend by submitting queries with a combination of filters, whatever the user has input. E.g., the user should be able to filter first on origin AS and then e.g., on service, and get the final table that contains entries filtered by both field values.

**Affected Component(s)**
- [ ] Back-End (Node.js, Next.js)
- [X] Front-End (React.js)
- [ ] Theming (CSS, React theme)
- [ ] Build System 
- [ ] Docs

**To Reproduce**
Steps to reproduce the behavior: Check it directly by filtering first on one field and then on the other.

**Expected behavior**
However the filters are used (in whatever order), the result should be correct.

**Screenshots**

**System (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by CuriouzK0d3r**
resolves #71

### CODE REVIEW

File: apps/artemis-web/libs/graphql.ts [hunk 1]
```diff
@@ -408,16 +408,18 @@ export class QueryGenerator {
...
-
-        if (column === 'service') {
-          condition = condition + `{ ${column}: {_like: "%${filterValue}%"} }`;
-        } else if (column !== 'as_path')
-          condition = condition + `{ ${column}: {_eq: "${filterValue}"} }`;
+        Object.keys(this.options.columnFilter).forEach((column) => {
+          const filterValue = this.options.columnFilter[column].filterVal;
+          if (column.includes('original'))
+            column = column.replace('_original', '');
+          else if (column === 'as_path2') column = 'as_path';
```
Comment (vkotronis) [inline apps/artemis-web/libs/graphql.ts:415]: why is this 'as_path2' used exact;y, and why not directly use 'as_path'?

File: apps/artemis-web/components/hijack-table/hijack-table.tsx [hunk 2]
```diff
@@ -578,17 +580,27 @@ const HijackTableComponent = (props) => {
...
+
+      keys.forEach((key) => {
+        if (filters[key])
+          setStateValues({ ...stateValues, [key]: filters[key].filterVal });
+        else setStateValues({ ...stateValues, [key]: '' });
+      });
+
+      if (currentIndex && !compareObjects(filters, columnFilter)) {
+        setPage(0);
+        setOffsetState(0);
```
Comment (vkotronis) [inline apps/artemis-web/components/hijack-table/hijack-table.tsx:601]: can we reuse some the same code used in the tables over and over (update + hijack tables)?

File: apps/artemis-web/libs/graphql.ts [hunk 3]
```diff
@@ -408,16 +408,18 @@ export class QueryGenerator {
...
+
+          if (column === 'service') {
+            condition =
+              condition + `{ ${column}: {_like: "%${filterValue}%"} }`;
+          } else if (column !== 'as_path')
+            condition = condition + `{ ${column}: {_eq: "${filterValue}"} }`;
```
Comment (vkotronis) [inline apps/artemis-web/libs/graphql.ts:421]: does this work if I search for AS paths including the filter ASN? (will check, just asking conceptually)

File: apps/artemis-web/utils/token.tsx [hunk 4]
```diff
@@ -112,6 +112,46 @@ export const statuses = {
...
+      result = false;
+    }
+
+    if (typeof obj1[key] === 'function' || typeof obj2[key] === 'function') {
+      if (obj1[key].toString() !== obj2[key].toString()) {
+        result = false;
+      }
+    }
+
+    if (!compareObjects(obj1[key], obj2[key])) {
```
Comment (vkotronis) [inline apps/artemis-web/utils/token.tsx:147]: I do not get this, is it recursive? (it seems to be contained in the body of the `compareObjects` definition)

**Review by vkotronis — COMMENTED** [review]
I will check prod deployment for testing, however please check the comments. It seems to me that we can reuse some the code which is repeated over and over in the different tables, but if there are slight modifications that prevent this reuse, you can ignore the comment.

**Comment by vkotronis** [comment]
Tried in prod, seems to work ok, but please check that the filtering logic is compatible with what we were doing in the old frontend. E.g., when a user looks for hijacks of specific type, the filter should be "like" so that e.g., he does not have to remember the entire sequence (for example, he should be able to search for type-0 hijacks without caring if they are subprefix for exact-prefix). So re-check what we were filtering in the initial frontend so that the functionality you have in the filters is a superset of that.

File: apps/artemis-web/libs/graphql.ts (hunk 1 above)
Comment (CuriouzK0d3r) [reply apps/artemis-web/libs/graphql.ts:415]: because as_path2 is a modified version of as_path, with added tooltips, I could also change this to use the as_path name, its no prob

File: apps/artemis-web/components/hijack-table/hijack-table.tsx (hunk 2 above)
Comment (CuriouzK0d3r) [reply apps/artemis-web/components/hijack-table/hijack-table.tsx:601]: yes we can

File: apps/artemis-web/utils/token.tsx (hunk 4 above)
Comment (CuriouzK0d3r) [reply apps/artemis-web/utils/token.tsx:147]: yes it is. it performs a deep equality check of JS objects

File: apps/artemis-web/libs/graphql.ts (hunk 1 above)
Comment (vkotronis) [reply apps/artemis-web/libs/graphql.ts:415]: OK then, probably it is fine, I was just worried that it was forgotten from mock naming. Resolving this comment.

File: apps/artemis-web/libs/graphql.ts (hunk 3 above)
Comment (vkotronis) [reply apps/artemis-web/libs/graphql.ts:421]: actually I checked and it seems to work, so I am resolving this conversation

File: apps/artemis-web/utils/token.tsx (hunk 4 above)
Comment (vkotronis) [reply apps/artemis-web/utils/token.tsx:147]: Thank you for the explanation Alex. Resolving.

File: apps/artemis-web/components/hijack-table/hijack-table.tsx (hunk 2 above)
Comment (vkotronis) [reply apps/artemis-web/components/hijack-table/hijack-table.tsx:601]: OK, please mark in the PR what can be reused e.g., as a function so that we reduce the probability of the same bug in two or more different places. This is sth general to consider for the code, but for now try to apply it here. It is also OK if it is not easily isolated in a function to leave as-is. In the latter case, you can resolve the comment.

**Review by vkotronis — APPROVED** [review]
LGTM!
