### PR TITLE
Duplication bug

### LINKED ISSUE #88: Multiple replicas are duplicated in dashboard
**Describe the bug**
Duplication of multi-replica entries in dashboard

**Affected Component(s)**
- [ ] Back-End (Node.js, Next.js)
- [X] Front-End (React.js)
- [ ] Theming (CSS, React theme)
- [ ] Build System 
- [ ] Docs

**To Reproduce**
```
docker-compose scale detection=2
```

**Expected behavior**
There should be only one entry with the needed sub-entries.

**Screenshots**
Screenshot_2021-04-26 ARTEMIS - Dashboard

**System (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by CuriouzK0d3r**
### Description of PR

What component(s) does this PR affect?

  - [ ] Back-End (Node.js, Next.js)
  - [X] Front-End (React.js)
  - [ ] Theming (CSS, React theme)
  - [ ] Build System
  - [ ] Docs
  
  
  
  Does the PR require changes on other components? If yes, please mark the components:
  
  - [ ] Back-End (Node.js, Next.js)
  - [ ] Front-End (React.js)
  - [ ] Theming (CSS, React theme)
  - [ ] Build System
  - [ ] Docs
  
  
  
### Related Issue
  
  
  
  
  
  
  Resolves #88 
  
### Type
  
  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)
  - [ ] Docs update
  - [ ] None of the above
  
  
  
### Checklist:
  
  - [ ] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
  - [ ] This change requires a change in the documentation.
  - [ ] I have updated the documentation accordingly.
  >)`>>>)>

### CODE REVIEW

**Review by vkotronis — COMMENTED** [review]
Seems to work great in dashboard. In the system page, I can see the changes when e.g., I spawn or remove replicas (`docker-compose scale <microservice>=<1,2,3,...>`), however the content of the buttons is not auto-refreshed except if I manually refresh the page. Could you please check if you have connected the buttons with async graphql state? After you check/fix this I will approve and then you can merge.

File: apps/artemis-web/pages/admin/system.tsx [hunk 1]
```diff
@@ -63,34 +64,38 @@ const SystemPage = (props) => {
     exabgptap: 'ExaBGP Monitor',
     detection: 'Detection',
     mitigation: 'Mitigation',
+    database: 'Database',
```
Comment (vkotronis) [inline apps/artemis-web/pages/admin/system.tsx:67]: Why is the database here? It is not a controllable service, it starts by default.

File: apps/artemis-web/components/status-table/status-table.tsx [hunk 2]
```diff
@@ -134,18 +139,30 @@ class StatusTable extends Component<StatsType, any> {
...
+                    process.name.slice(0, process.name.indexOf('-'))
+                  )
+                ) {
+                  backList.push(
+                    process.name.slice(0, process.name.indexOf('-'))
+                  );
+
+                  return (
+                    <ModuleState
+                      key={i}
```
Comment (vkotronis) [inline apps/artemis-web/components/status-table/status-table.tsx:153]: please put some comments in the code, it is very hard for an outside dev to understand why e.g., you are using this index etc. Briefly comment your blocks of code, otherwise we will not be able to maintain them on the long run.

File: apps/artemis-web/pages/admin/system.tsx [hunk 3]
```diff
@@ -109,17 +114,22 @@ const SystemPage = (props) => {
...
-                        {...props}
-                        key={i}
-                        module={module}
-                        subModules={subModules}
-                        labels={modulesLabels}
-                        state={state}
-                        setState={setState}
-                      />
-                    );
+                    const key = module
```
Comment (vkotronis) [inline apps/artemis-web/pages/admin/system.tsx:117]: same here, please comment.

File: apps/artemis-web/pages/admin/system.tsx [hunk 4]
```diff
@@ -63,34 +64,38 @@ const SystemPage = (props) => {
...
-  const keys = Object.keys(state).filter((key) =>
+  // const [state, setState] = useState(states);
+  let stateRT = states;
+
+  let keys = Object.keys(stateRT).filter((key) =>
     modulesList.includes(key.substring(0, key.indexOf('-')).toLowerCase())
   );
+
   const subModules = {};
   keys.forEach((key) => {
```
Comment (vkotronis) [inline apps/artemis-web/pages/admin/system.tsx:79]: same here please comment what the code does

File: apps/artemis-web/pages/admin/system.tsx [hunk 5]
```diff
@@ -63,34 +64,38 @@ const SystemPage = (props) => {
...
     detection: 'Detection',
     mitigation: 'Mitigation',
+    database: 'Database',
   };
 
   modules.forEach((module) => (states[module[0].toString()] = module[1]));
-  const [state, setState] = useState(states);
-  const keys = Object.keys(state).filter((key) =>
+  // const [state, setState] = useState(states);
+  let stateRT = states;
```
Comment (vkotronis) [inline apps/artemis-web/pages/admin/system.tsx:72]: stateRT means real-time state? Two options:
1. Either use clearer names
2. Comment on what it means so that the reader knows how it is used in the rest of the code

**Review by vkotronis — CHANGES_REQUESTED** [review]
I left some comments here, most important is to properly comment on what you do in some block codes for maintenability. Also, please check if it is possible to display (in both overview and system pages) with yellow services that are essentially not fully booted (e.g., 1/3, 4/5, etc.). Red is used fine if everything is off, green should be used when everything is on. If it is not possible you can leave as-is to address separately (not critical).

File: apps/artemis-web/pages/admin/system.tsx (hunk 1 above)
Comment (CuriouzK0d3r) [reply apps/artemis-web/pages/admin/system.tsx:67]: Oh no, I was testing something, and forgot to remove this!

**Review by vkotronis — APPROVED** [review]
Looks good now, thanks!
